name: flutter_quan_li_tai_chinh
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_toggle_tab: ^1.4.1
  syncfusion_flutter_charts: ^24.1.47+2
  sign_in_button: ^3.2.0
  firebase_auth: ^4.17.6
  firebase_core: ^2.25.5
  google_sign_in: ^6.2.1
  fl_chart: ^0.66.2
  font_awesome_flutter: ^10.7.0
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/item_icon/
    - assets/wallet_icon/
