// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRuPv9zYNMie_xJlbZ7-m3Uxf1YqnilP8',
    appId: '1:514802221636:web:f3c0f78d53732ffbd97211',
    messagingSenderId: '514802221636',
    projectId: 'quan-ly-chi-tieu-8dff9',
    authDomain: 'quan-ly-chi-tieu-8dff9.firebaseapp.com',
    storageBucket: 'quan-ly-chi-tieu-8dff9.appspot.com',
    measurementId: 'G-J6FHM30QLG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChOjf8fsgu06s6eshiUrk0fMteu-5uSRQ',
    appId: '1:514802221636:android:04ff3b598cf012fbd97211',
    messagingSenderId: '514802221636',
    projectId: 'quan-ly-chi-tieu-8dff9',
    storageBucket: 'quan-ly-chi-tieu-8dff9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhIWno7f24SpBsOr5mKuQcDAv8y8kinCA',
    appId: '1:514802221636:ios:772e0a230feb920cd97211',
    messagingSenderId: '514802221636',
    projectId: 'quan-ly-chi-tieu-8dff9',
    storageBucket: 'quan-ly-chi-tieu-8dff9.appspot.com',
    iosBundleId: 'com.example.flutterQuanLiTaiChinh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhIWno7f24SpBsOr5mKuQcDAv8y8kinCA',
    appId: '1:514802221636:ios:9d28e0d4489646bcd97211',
    messagingSenderId: '514802221636',
    projectId: 'quan-ly-chi-tieu-8dff9',
    storageBucket: 'quan-ly-chi-tieu-8dff9.appspot.com',
    iosBundleId: 'com.example.flutterQuanLiTaiChinh.RunnerTests',
  );
}
